<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>
  
  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>

	<ItemGroup>
		<PackageReference Include="Avalonia" />
		<PackageReference Include="Avalonia.Controls.DataGrid" />
		<PackageReference Include="Avalonia.Controls.TreeDataGrid" />
		<PackageReference Include="Avalonia.Themes.Fluent" />
		<PackageReference Include="Avalonia.Fonts.Inter" />
		<PackageReference Include="Avalonia.Diagnostics" >
			<IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
			<PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
		</PackageReference>
		<PackageReference Include="LiveChartsCore.SkiaSharpView.Avalonia" />
		<PackageReference Include="Newtonsoft.Json" />
		<PackageReference Include="ReactiveUI.Fody" />
		<PackageReference Include="Avalonia.ReactiveUI" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" />
	</ItemGroup>
</Project>
