<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>
  
  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>
  
  <ItemGroup>
    <Compile Remove="services\interfaces\Interface1.cs" />
  </ItemGroup>
  
  <ItemGroup>
    <Compile Include="obj\Debug\net8.0\.NETCoreApp,Version=v8.0.AssemblyAttributes.cs" />
    <Compile Include="obj\Debug\net8.0\client.AssemblyInfo.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.6" />
    <PackageReference Include="Avalonia.Controls.DataGrid" Version="11.3.6" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.6" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.6" />

    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Controls.DataGrid" />
    <PackageReference Include="Avalonia.Controls.TreeDataGrid" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <PackageReference Include="Avalonia.Fonts.Inter" />
    <PackageReference Include="Avalonia.Diagnostics" Version="11.3.6">
      <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
      <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Avalonia.ReactiveUI" />
    <PackageReference Include="LiveChartsCore.SkiaSharpView.Avalonia" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="ReactiveUI.Fody" />
    <PackageReference Include="Avalonia.ReactiveUI" Version="11.3.6" />
    <PackageReference Include="Microsoft.AspNetCore.Hosting" Version="2.3.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.9" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="bin\Debug\net8.0\" />
    <Folder Include="obj\Debug\net8.0\refint\" />
    <Folder Include="obj\Debug\net8.0\ref\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="obj\Debug\net8.0\client.AssemblyInfoInputs.cache" />
    <None Include="obj\Debug\net8.0\client.GeneratedMSBuildEditorConfig.editorconfig" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Models\" />
  </ItemGroup>
</Project>
