<Project Sdk="Microsoft.NET.Sdk.WebAssembly">
  <PropertyGroup>
    <TargetFramework>net8.0-browser</TargetFramework>
    <OutputType>Exe</OutputType>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Browser" />
    <PackageReference Include="Avalonia.Controls.DataGrid" />
    <PackageReference Include="Avalonia.Controls.TreeDataGrid" />
    <PackageReference Include="LiveChartsCore.SkiaSharpView.Avalonia" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\client\client.csproj" />
  </ItemGroup>
</Project>
